name: github pages

on:
  push:
    branches:
      - master

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.0
        with:
          username: 'orlovrs'
          reponame: 'json-parser'
          token: ${{ secrets.GITHUB_TOKEN }}